### ISSUE TITLE
Working Client Info

### ISSUE THREAD

**Issue by asheimo** [contrary-cat/LocalTVExtras.bundle#11]
Got this from one of the issues, Could you please list this in your readme as well so that it is easily findable. I'm sure the community would be happy to keep you updates if changes are found. Thanks

I don't have all these clients myself, so this is mostly a summary of what I have been told on the [thread in the plex forums](https://forums.plex.tv/t/local-tv-extras-agent/226648).

Episodes only:
* iOS client
(not sure why this is, this seems to be the only client that supports TV extras only on episodes)

Show only:
* Plex Media Player
* Plex Web Client

Show and Season:
* Roku Client (reported on [6th January](https://forums.plex.tv/t/local-tv-extras-agent/226648/62), hopefully the recent updates haven't changed this)
* Kodi with the [official Plex Add-on](https://kodi.tv/addon/scripts-video-add-ons/plex)
 (This also includes MRMC with the same Plex Add-on, which is a tolerable experience on AppleTV, but not good on iOS in my opinion)

Show, Season and Episode:
* The Android client (I believe that this includes Android TV/NVIDIA Shield as well as Android Phones & Tablets)

No TV Extras:
* The Apple TV client

The ones I can personally confirm are Plex Web (naturally), Plex Media Player, Plex for Kodi, iOS and Apple TV.

The quickest way to see your season extras would probably be to download Kodi and install the Plex for Kodi add-on.

_Originally posted by @contrary-cat in https://github.com/contrary-cat/LocalTVExtras.bundle/issues/2#issuecomment-489430934_

**Comment by contrary-cat** [comment]
Thanks for the suggestion – I've added the info to the end of the readme, and hopefully my Android & Roku information is still up-to-date
