### ISSUE TITLE
[Request] Section for each type

### ISSUE THREAD

**Issue by MrsAngelD** [contrary-cat/LocalTVExtras.bundle#5]
Hi, thanks for this, I love that I can have access to my extras!

I was wondering if it were possible to have a row for each type of extra (ie..trailers, featurettes, Interviews..etc).

Some shows have tons of extra's and it would be so much easier if they were broken down into sections instead of one row for every extra.

In any case thank you so much for this!

**Comment by contrary-cat** [comment]
I'm glad you've found the agent useful - thanks for letting me know

I agree that splitting the different types into rows would be a nice feature, unfortunately that's something that would have to be added to the different Plex clients - metadata agents like this one give the server information to include, but don't have much input on the way it is laid out.

You could add a feature request in the Plex forums, though: [feature Suggestions forum](https://forums.plex.tv/c/general/feature-suggestions)
