### ISSUE TITLE
ValidatePrefs

### ISSUE THREAD

**Issue by kchiem** [contrary-cat/LocalTVExtras.bundle#8]
This doesn't seem to be working for me.  Seeing this in the logs:

... CRITICAL (sandbox:298) - Function named 'ValidatePrefs' couldn't be found in the current environment

**Comment by contrary-cat** [comment]
The agent currently doesn't have a function that checks that the values entered for preferences are valid, so Plex logs that the function can't be found. However I don't think this has caused any issues in how the agent functions - preferences are still respected and the extras are found and added.

If you navigate to the show you want to add extras in, and refresh metadata for that show, then the extras should be added as long as they match the required naming scheme. If it doesn't work for you, please attach the com.plexapp.agents.localtvextras.log file once the metadata refresh is complete.
